name: peek
description: "Peek - Anonymous photo request app"
publish_to: 'none' # private project

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase core tools
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  firebase_in_app_messaging: ^0.8.1+5
  firebase_ui_auth: ^1.14.0

  # Subscriptions & payments
  in_app_purchase: ^3.2.1

  # Local storage & UUID
  shared_preferences: ^2.2.2
  uuid: ^4.4.2

  # Routing & state management
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

  # UI enhancements
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.8

  # Camera / photo
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
