// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KWlLtsoJgzN-CWHlnNlMJFWcJuJoB_c',
    appId: '1:96119580821:web:263dc3bbd59cb77e17939c',
    messagingSenderId: '96119580821',
    projectId: 'peek-fire',
    authDomain: 'peek-fire.firebaseapp.com',
    storageBucket: 'peek-fire.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFctI-qM68_pf2VSxH5qNJMbxQRdSfnbs',
    appId: '1:96119580821:android:5a073baaaedf340e17939c',
    messagingSenderId: '96119580821',
    projectId: 'peek-fire',
    storageBucket: 'peek-fire.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtTWVA82YltlEc9OnrYGQ44p6bsPmPSFg',
    appId: '1:96119580821:ios:889ce1d2cd69dd8117939c',
    messagingSenderId: '96119580821',
    projectId: 'peek-fire',
    storageBucket: 'peek-fire.firebasestorage.app',
    iosBundleId: 'com.example.peek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtTWVA82YltlEc9OnrYGQ44p6bsPmPSFg',
    appId: '1:96119580821:ios:889ce1d2cd69dd8117939c',
    messagingSenderId: '96119580821',
    projectId: 'peek-fire',
    storageBucket: 'peek-fire.firebasestorage.app',
    iosBundleId: 'com.example.peek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1KWlLtsoJgzN-CWHlnNlMJFWcJuJoB_c',
    appId: '1:96119580821:web:de29393a0867828b17939c',
    messagingSenderId: '96119580821',
    projectId: 'peek-fire',
    authDomain: 'peek-fire.firebaseapp.com',
    storageBucket: 'peek-fire.firebasestorage.app',
  );
}
