// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcwck7BYvsEh6KUpSyFYyR4PpQok_VXbA',
    appId: '1:458153260208:web:2819def88574cc1b30f775',
    messagingSenderId: '458153260208',
    projectId: 'peekio-db',
    authDomain: 'peekio-db.firebaseapp.com',
    storageBucket: 'peekio-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtvrAWS-wmC3pobfprw9ElCNyUKFp1grI',
    appId: '1:458153260208:android:1d3ff67e6429f6cf30f775',
    messagingSenderId: '458153260208',
    projectId: 'peekio-db',
    storageBucket: 'peekio-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHh_zpl6jb1Hp9rN1sUGZbazRnJKFZCHA',
    appId: '1:458153260208:ios:35922ed5e28d6a9730f775',
    messagingSenderId: '458153260208',
    projectId: 'peekio-db',
    storageBucket: 'peekio-db.firebasestorage.app',
    iosClientId: '458153260208-o07aepatsq9sjdltm0re07fk8eoq868e.apps.googleusercontent.com',
    iosBundleId: 'com.fab.peek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHh_zpl6jb1Hp9rN1sUGZbazRnJKFZCHA',
    appId: '1:458153260208:ios:35922ed5e28d6a9730f775',
    messagingSenderId: '458153260208',
    projectId: 'peekio-db',
    storageBucket: 'peekio-db.firebasestorage.app',
    iosClientId: '458153260208-o07aepatsq9sjdltm0re07fk8eoq868e.apps.googleusercontent.com',
    iosBundleId: 'com.fab.peek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcwck7BYvsEh6KUpSyFYyR4PpQok_VXbA',
    appId: '1:458153260208:web:670a5d4d16dc615830f775',
    messagingSenderId: '458153260208',
    projectId: 'peekio-db',
    authDomain: 'peekio-db.firebaseapp.com',
    storageBucket: 'peekio-db.firebasestorage.app',
  );

}