// lib/features/menu/privacy_page.dart
import 'package:flutter/material.dart';
import 'package:peek/theme/colors.dart';
import 'package:go_router/go_router.dart';

class PrivacyPage extends StatelessWidget {
  const PrivacyPage({super.key});

  static const String _privacyPolicyText = """
# Privacy Policy for Peekio App

**Last Updated: May 15, 2025**

Welcome to Peekio! Your privacy and anonymity are at the core of our service. This Privacy Policy explains how [Your Company Name/Your Name if individual developer] ("we," "us," or "our") handles information in relation to our mobile application Peekio (the "Service"). Our goal is to provide a fun, spontaneous experience with the utmost respect for your privacy, collecting and storing the absolute minimum information necessary for the app to function.

**Peekio is designed so that you are not required to register a traditional account with personal identifiers like your name, email address, or phone number to use its core features.**

By downloading, accessing, or using the Peekio app, you agree to the terms of this Privacy Policy. If you do not agree with the terms, please do not use the Service.

## 1. Our Commitment to Anonymity and Minimal Data

* **No Registration for Core Use:** You can use Peekio's core features without creating an account that requires personal identification.
* **Ephemeral Content:** Photos ("Peeks") you send are designed to be temporary and are not stored by us on our active servers long-term after delivery or a short operational window.
* **Minimal Data Collection:** We strive to collect only the data essential for the operation, security, and improvement of the Service. We do not seek to identify you personally.

## 2. What "Anonymous" Means for Peekio

When we refer to "anonymous," we mean:
* We do not require you to provide your real name, email, phone number, or other direct personal identifiers to use the core Peekio service.
* Interactions (sending/receiving Peeks) are designed to occur without revealing such personal identifiers between users.
* While the Service may use pseudonymous identifiers (like those generated by Firebase Anonymous Authentication, or device identifiers for analytics/crash reporting), these are not linked by us to your real-world identity.

## 3. Information We Do NOT Collect or Store (by Us Directly)

* We do **not** ask for or store your real name, email address (unless you voluntarily provide it for support), phone number, or physical address for the core functionality of the app.
* We do **not** build user profiles based on your activity for the purpose of ad targeting by us.
* We do **not** store the content of Peeks (photos) on our active servers long-term after they have been delivered or the request has expired/been declined. Their handling is designed to be ephemeral.

## 4. Information We Process (and Why)

Even in an anonymous system, some data processing is necessary for the app to function and improve.

**a. Data Processed for Core Functionality:**
* **Peek Content (Photos):** When you send a Peek, the photo is transmitted through our systems (or those of our service providers like Firebase Storage) to the recipient. This data is processed for the sole purpose of delivery and is intended to be deleted from our active operational servers shortly after successful delivery or if the request times out or is declined. We do not claim ownership of this content.
* **Reactions (Likes/Dislikes):**
    * If you react to a Peek, that reaction (like/dislike) is sent to the original sender of the Peek.
    * To provide the "My Stats" feature (for premium users), we store aggregated counts of likes and dislikes received, associated with an internal, non-personally identifiable user ID (e.g., a Firebase Anonymous Auth UID). This data is not shared with other users beyond the individual user viewing their own stats.
* **Anonymous User Identifiers:** If you use features that require some form of session persistence or user-specific data (like premium status or stats), the Service may use an anonymous or pseudonymous identifier (e.g., provided by Firebase Anonymous Authentication). This identifier is not linked by us to your real-world identity.
* **Location Information (Optional & With Your Explicit Consent):**
    * If you choose to enable location sharing for Peeks you send, and only if you grant explicit permission through your device's operating system, we may process your general location (e.g., city/region) to share it with the Peek recipient (if they are a premium user with the feature enabled).
    * This feature is strictly opt-in. You can enable or disable location services for Peekio at any time via your device settings. We do not store your precise location history.
* **Premium Subscription Data:** If you subscribe to Peekio Premium, our third-party payment processors (Apple App Store or Google Play Store) will collect payment information. We do not receive or store your full credit card details. We receive information from the app stores about your subscription status (e.g., active, expired) to manage your premium access. This is typically linked to your app store account and an anonymous/pseudonymous ID within our system.

**b. Automatically Processed Operational & Technical Data:**
* **Device and Connection Information:** We (or our third-party service providers like Firebase) may automatically process certain technical information such as your device type, operating system version, IP address (which may provide a general location), app version, and unique device identifiers (like IDFA or Android Advertising ID, if platform policies allow and you consent). This information is essential for:
    * Delivering the Service (e.g., routing data).
    * Security and fraud prevention.
    * Troubleshooting, crash reporting (e.g., via Firebase Crashlytics).
    * Basic, aggregated, and anonymized analytics to understand service usage and improve performance (e.g., via Firebase Analytics).
* **Usage Data (Aggregated & Anonymized):** We may collect aggregated and anonymized information about how the Service is used (e.g., feature popularity, number of Peeks sent/received in total across the platform). This data does not identify individual users.

**c. Communications with Us:**
* If you voluntarily contact us for support or feedback (e.g., via email), we will process the information you provide (which might include your email address or name) solely to address your inquiry.

## 5. How We Use Processed Information

Any information processed is used for the following limited purposes:
* **Operating and Delivering the Service:** Authenticating users (anonymously where applicable), transmitting Peeks and reactions, managing premium subscriptions.
* **Maintaining and Improving the Service:** Understanding usage patterns (on an aggregated, anonymous basis), identifying and fixing bugs or crashes, developing new features.
* **Security and Safety:** Protecting against abuse, fraud, or security threats; enforcing our terms.
* **Legal Compliance:** Complying with applicable legal obligations.

## 6. How We Share (or Do NOT Share) Information

Your privacy and anonymity are paramount.
* **We do NOT sell your personal information.**
* **Between Users:** Peeks are shared between users as per the app's functionality. If location sharing is enabled by the sender and the recipient has the feature, generalized location is shared. Anonymous UIDs are used for routing but are not designed to be directly identifiable by other users.
* **Service Providers:** We may use third-party service providers for essential functions like cloud hosting (e.g., Firebase for photo storage/transmission, database), analytics (e.g., Firebase Analytics for aggregated, anonymized data), crash reporting (e.g., Firebase Crashlytics), and payment processing for subscriptions (Apple/Google). These providers only have access to the information necessary to perform their functions and are obligated not to disclose or use it for other purposes. We encourage you to review their privacy policies.
    * Firebase: [https://firebase.google.com/policies/privacy](https://firebase.google.com/policies/privacy)
* **Aggregated/De-Identified Data:** We may share data that is aggregated or de-identified (and thus not personally identifiable) for research, statistical analysis, or reporting.
* **Legal Reasons:** We may disclose information if required by law or if we believe in good faith that such action is necessary to comply with legal processes, protect our rights or property, ensure the safety of our users or the public, or prevent illegal activities.
* **Business Transfers:** If we are involved in a merger, acquisition, financing, or sale of assets, information may be transferred as part of that transaction, subject to standard confidentiality agreements.

## 7. Data Retention and Deletion

* **Peek Photos:** Designed to be ephemeral. We aim to delete them from our active operational systems shortly after delivery or expiration/rejection.
* **Anonymous/Pseudonymous Identifiers & Associated Data (e.g., Stats, Premium Status):** Retained as long as necessary to provide the service features associated with that identifier or until you request deletion (where technically feasible and not conflicting with legal obligations).
* **Operational Logs (e.g., IP addresses):** May be retained for a limited period for security and troubleshooting purposes.

## 8. Security

We implement reasonable technical and organizational measures to protect the information we process. However, no internet or email transmission is ever fully secure or error-free. While we strive to protect your information, we cannot guarantee its absolute security.

## 9. Children's Privacy

Peekio is not directed to individuals under the age of 13 (or the relevant age of consent in your jurisdiction). We do not knowingly collect personal information from children. If you believe a child has provided us with information in violation of this policy, please contact us immediately.

## 10. Your Rights (GDPR, CCPA, and other applicable laws)

Depending on your jurisdiction, you may have certain rights regarding your information. Given the anonymous/pseudonymous nature of much of the data Peekio processes:
* **Access & Portability:** If you have an anonymous identifier associated with data like premium status or stats, you may be able to request access to this data.
* **Correction:** If any data associated with your anonymous identifier is incorrect, you may have the right to request its correction.
* **Deletion ("Right to be Forgotten"):** You may have the right to request the deletion of data associated with your anonymous identifier. Deleting and reinstalling the app may reset some locally stored identifiers or data processed by third-party SDKs. For server-side data linked to an anonymous ID (like stats), please contact us.
* **Opt-Out of Location Sharing:** You can disable this at any time in your device settings.

To exercise these rights, or if you have questions about them, please contact us. We will respond in accordance with applicable law. For us to process requests related to data associated with an anonymous identifier, you may need to provide information that helps us locate that specific identifier (e.g., the anonymous UID itself if you can access it).

## 11. Third-Party Services

As mentioned, Peekio may utilize third-party services (e.g., Firebase for backend functionality, analytics, crash reporting; Apple/Google for payment processing). These services have their own privacy policies that govern their use of your information. We encourage you to review them.

## 12. Changes to This Privacy Policy

We may update this Privacy Policy from time to time. The "Last Updated" date at the top of this policy will indicate when it was last revised. We encourage you to review this policy periodically. Your continued use of the Service after any changes constitutes your acceptance of the new Privacy Policy. For material changes, we may provide more prominent notice.

## 13. Contact Us

If you have any questions, concerns, or comments about this Privacy Policy or our data practices, please contact us at:

White Stitch
Email: support@peekio.app
Website: www.peekio.app
""";

  List<Widget> _buildPolicyWidgets(BuildContext context, String policyText) {
    final List<Widget> widgets = [];
    final lines = policyText.split('\n');
    final TextTheme textTheme = Theme.of(context).textTheme;
    final boldStyle = textTheme.bodyMedium?.copyWith(
        color: peekOnBackgroundColor, fontWeight: FontWeight.w600, height: 1.5);
    final regularStyle = textTheme.bodyMedium
        ?.copyWith(color: peekOnBackgroundColor.withOpacity(0.9), height: 1.5);

    for (String line in lines) {
      line = line.trim();
      if (line.startsWith('## ')) {
        widgets.add(
          Padding(
            padding: const EdgeInsets.only(top: 20.0, bottom: 8.0),
            child: Text(
              line.substring(3),
              style: textTheme.headlineSmall?.copyWith(
                color: peekOnBackgroundColor,
                fontWeight: FontWeight.w600,
                fontSize: 22,
              ),
            ),
          ),
        );
      } else if (line.startsWith('# ')) {
        widgets.add(
          Padding(
            padding: const EdgeInsets.only(top: 24.0, bottom: 12.0),
            child: Text(
              line.substring(2),
              style: textTheme.headlineMedium?.copyWith(
                color: peekPrimaryColor,
                fontSize: 22,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        );
      } else if (line.startsWith('* **')) {
        // Handles lines like: * **Bold part:** Regular part
        int boldEndIndex = line.indexOf('**', 3); // Find second '**'
        if (boldEndIndex != -1) {
          String boldPart =
              line.substring(3, boldEndIndex); // Text between * ** and **
          String restPart =
              line.substring(boldEndIndex + 2); // Text after second **

          widgets.add(
            Padding(
              padding: const EdgeInsets.only(left: 16.0, top: 4.0, bottom: 4.0),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text("•  ",
                      style: boldStyle?.copyWith(fontSize: 16)), // Bullet point
                  Expanded(
                    child: Text.rich(
                      TextSpan(
                        children: [
                          TextSpan(text: boldPart, style: boldStyle),
                          TextSpan(text: restPart, style: regularStyle),
                        ],
                      ),
                      // textAlign: TextAlign.justify,
                    ),
                  ),
                ],
              ),
            ),
          );
        } else {
          // Fallback if format is unexpected
          widgets.add(
            Padding(
              padding: const EdgeInsets.only(left: 16.0, top: 4.0, bottom: 4.0),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text("•  ",
                      style: TextStyle(
                          color: peekOnBackgroundColor, fontSize: 16)),
                  Expanded(
                    child: Text(
                      line.substring(2), // Remove "* "
                      style: regularStyle,

                      // textAlign: TextAlign.justify,
                    ),
                  ),
                ],
              ),
            ),
          );
        }
      } else if (line.startsWith('* ')) {
        widgets.add(
          Padding(
            padding: const EdgeInsets.only(left: 16.0, top: 4.0, bottom: 4.0),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text("•  ",
                    style: TextStyle(
                        color: peekOnBackgroundColor,
                        fontSize: 16)), // Added more space after bullet
                Expanded(
                  child: Text(
                    line.substring(2),
                    style: regularStyle,
                    // textAlign: TextAlign.justify,
                  ),
                ),
              ],
            ),
          ),
        );
      } else if (line.startsWith('**') &&
          line.endsWith('**') &&
          line.length > 4) {
        widgets.add(
          Padding(
            padding: const EdgeInsets.only(top: 8.0, bottom: 8.0),
            child: Text(
              line.substring(
                  2, line.length - 2), // Remove starting and ending **
              style: boldStyle,
              // textAlign: TextAlign.justify,
            ),
          ),
        );
      } else if (line.isNotEmpty) {
        widgets.add(
          Padding(
            padding: const EdgeInsets.only(top: 8.0, bottom: 8.0),
            child: Text(
              line,
              style: regularStyle,
              // textAlign: TextAlign.justify,
            ),
          ),
        );
      } else {
        widgets.add(const SizedBox(height: 10.0));
      }
    }
    return widgets;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: peekBackgroundColor,
      appBar: AppBar(
        title: const Text('Privacy Policy'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new),
          onPressed: () {
            if (context.canPop()) {
              context.pop();
            } else {
              context.go('/');
            }
          },
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.symmetric(horizontal: 20.0, vertical: 16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: _buildPolicyWidgets(context, _privacyPolicyText),
        ),
      ),
    );
  }
}
